### ISSUE TITLE
exception on khamake android --from --to

### ISSUE THREAD

**Issue by JeriXNet** [KTXSoftware/koremake#2]
I've caught this exception when tried to run khamake with command similar to this:
node Kha/make android --from c:\path\to\project_dir --to c:\path\to\project_dir\build
and exception looks something like this:
```
Error: ENOENT, no such file or directory 'c:\path\to\project_dir\build\android-build\assets\c:'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at Object.exports.createDirectories (c:\projects\jerix_net\fsq_socks_src\Kha\Kore\Tools\koremake\Files.js:39:7)
    at Exporter.createDirectory (c:\projects\jerix_net\fsq_socks_src\Kha\Kore\Tools\koremake\Exporter.js:41:32)
    at Exporter.copyDirectory (c:\projects\jerix_net\fsq_socks_src\Kha\Kore\Tools\koremake\Exporter.js:31:7)
    at Exporter.copyDirectory (c:\projects\jerix_net\fsq_socks_src\Kha\Kore\Tools\koremake\Exporter.js:35:37)
    at ExporterAndroid.exportSolution (c:\projects\jerix_net\fsq_socks_src\Kha\Kore\Tools\koremake\ExporterAndroid.js:21:45)
    at exportKakeProject (c:\projects\jerix_net\fsq_socks_src\Kha\Kore\Tools\koremake\main.js:178:11)
    at exportProject (c:\projects\jerix_net\fsq_socks_src\Kha\Kore\Tools\koremake\main.js:190:10)
    at Object.exports.run (c:\projects\jerix_net\fsq_socks_src\Kha\Kore\Tools\koremake\main.js:215:21)
```

**Comment by RobDangerous** [comment]
I'm on it, saw your message :)

**Comment by RobDangerous** [comment]
Think it's fixed, can you check?

**Comment by JeriXNet** [comment]
Just updated kha and tested it - it's working ok now, thanks.

**Comment by RobDangerous** [comment]
Okidoki
